"""AI Suggestion model - Suggerimenti generati dall'AI con workflow di approvazione."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from src.infrastructure.database.base import Base


class AISuggestionStatus:
    """Status values for AI suggestions."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    MODIFIED = "modified"


class AISuggestion(Base):
    """AI-generated suggestions for noise assessment.

    Suggestions are generated by AI and must be validated
    by a human consultant before being used.
    """

    __tablename__ = "ai_suggestion"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenant.id"), nullable=False, index=True
    )

    # Context — legacy assessment_id (Wave 16-23) + new context_id (Wave 27)
    assessment_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        index=True,
        comment="Legacy NoiseAssessment reference (pre-MARS integration)",
    )
    context_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("noise_assessment_context.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
        comment="MARS-bound NoiseAssessmentContext reference (Wave 27+)",
    )
    interaction_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
        comment="Reference to AI interaction that generated this",
    )

    # Suggestion content
    suggestion_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        comment="Type: process, machine, role, mitigation, narrative",
    )
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    content: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        comment="Structured suggestion content as JSON",
    )

    # Classification
    risk_band: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="Related risk band if applicable",
    )
    priority: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="Priority order (1=highest)",
    )

    # Validation
    confidence_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="AI confidence in suggestion (0.0-1.0)",
    )
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default=AISuggestionStatus.PENDING,
        index=True,
    )
    approved_by: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        comment="Email or identifier of approver",
    )
    approved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    rejection_reason: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # Versioning
    version: Mapped[int] = mapped_column(
        Integer,
        default=1,
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
    )

    def __repr__(self) -> str:
        return f"<AISuggestion(id={self.id}, type='{self.suggestion_type}', status='{self.status}')>"
